services:
  nas-sync:
    image: ghcr.io/seraphofnineball/nas-sync:latest
    container_name: nas-sync
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./data:/data
      - /volume1:/volume1
      - /mnt/@usb:/mnt/@usb
